import{g as E,m as u,a as L,b as M,c as B,d as A}from"./assets/applebooks@2x-b02de412.js";const v="https://books-backend.p.goit.global/books",_={list:"category-list",top:"top-books",category:"category?category="};async function P(e,t=""){try{const o=await fetch(`${v}/${e}${t}`),r=await o.json();return console.log(`data retrieving was succesfull: ${o.status} - ${o.statusText}`),r}catch(o){console.log(`An error occurred: ${o.message}`),alert("An error occurred")}}async function N(e){try{const t=await fetch(`${v}/${e}`),o=await t.json();return console.log(`data retrieving was succesfull: ${t.status} - ${t.statusText}`),o}catch(t){console.log(`An error occurred: ${t.message}`),alert("An error occurred")}}const s={API_OPTIONS:_,fetchBookList:P,fetchBookById:N},z=document.querySelector(".ctg-list");s.fetchBookList(s.API_OPTIONS.list).then(e=>{const t=e.map(({list_name:o})=>`<li class="ctg-item js-ctg-item " data-ctg-name = ${o}>${o}
          </li>`).join("");z.insertAdjacentHTML("beforeend",t)});const c=E();s.fetchBookList(s.API_OPTIONS.top).then(u.renderTopBooks);function w(e){[...c.ctgList.children].forEach(t=>t.classList.remove("ctg-item-active")),c.ctgList.contains(e.target)?e.target.classList.add("ctg-item-active"):[...c.ctgList.children].find(o=>o.textContent.trim()===e.target.dataset.category).classList.add("ctg-item-active")}function j(e){const t=e.target.childNodes[0].data;w(e),t!=="All categories"?s.fetchBookList(s.API_OPTIONS.category,t).then(u.renderCategoryBooks):s.fetchBookList(s.API_OPTIONS.top).then(u.renderTopBooks)}function R(e){if(!e.target.classList.contains("top-books-button"))return;const t=e.target.dataset.category;w(e),s.fetchBookList(s.API_OPTIONS.category,t).then(u.renderCategoryBooks)}c.ctgList.addEventListener("click",j);c.bookCollectionWrapper.addEventListener("click",R);const D=E(),f=document.getElementById("bookModal"),h=document.getElementById("bookModalTitle"),H=document.getElementById("bookModalBody"),l=document.getElementById("addToShoppingList"),J=document.querySelector(".modal-close");let i=[],m=[],S={};function q(e){s.fetchBookById(e).then(t=>{h.innerText=t.title,S={book_image:t.book_image,title:t.title,author:t.author,description:t.description,amazonLinks:t.buy_links[0].url,appleLinks:t.buy_links[1].url},h.dataset.bookId=e,H.innerHTML=`<img src="${t.book_image}" alt="${t.title}" class="book-modal-img"/>
            <div class="book-modal-details">
                <h2 class="book-modal-title">${t.title}</h2>
                <h3 class="book-modal-author">${t.author}</h3>
                <p class="book-modal-desc">${t.description}</p>
                <ul class="icon-book-modal-list">
                    <li>
                        <a href="${t.buy_links[0].url}" rel="noopener noreferrer nofollow" target="_blank">
                            <img class="icon-book-modal-amazon" srcset="${L} 1x, ${M} 2x" src="${L}" alt="Amazon" loading="lazy"/>
                        </a>
                    </li>
                    <li>
                        <a href="${t.buy_links[1].url}" rel="noopener noreferrer nofollow" target="_blank">
                            <img class="icon-book-modal-ibooks" srcset="${B} 1x, ${A} 2x" src="${B}" alt="Apple books" loading="lazy"/>
                        </a>
                    </li>
                </ul>
            </div>
    `,i.includes(e)?l.innerText="Remove from the shopping list":l.innerText="Add to shopping list",f.classList.add("show"),document.body.style.overflow="hidden"})}function k(){f.classList.remove("show"),document.body.style.overflow=""}function F(e){if(console.log("Toggling shopping list for bookId:",e),!e){console.error("Invalid bookId:",e);return}const t=i.indexOf(e);t===-1?(i.push(e),m.push(S)):(i.splice(t,1),m.splice(t,1)),console.log("Updated shoppingList:",i),localStorage.setItem("shoppingList",JSON.stringify(i)),localStorage.setItem("shoppingCard",JSON.stringify(m)),t===-1?l.innerText="Remove from the shopping list":l.innerText="Add to shopping list"}l.addEventListener("click",()=>{const e=h.dataset.bookId;F(e)});f.addEventListener("click",e=>{e.target===f&&k()});document.addEventListener("keydown",e=>{e.key==="Escape"&&k()});D.bookCollectionWrapper.addEventListener("click",e=>{const t=e.target.closest(".book-link");if(t){e.preventDefault();const o=t.dataset.id;q(o)}});const b=localStorage.getItem("shoppingList"),I=localStorage.getItem("shoppingCard");b&&(i=JSON.parse(b));I&&(m=JSON.parse(I));J.addEventListener("click",k);document.addEventListener("DOMContentLoaded",function(){document.getElementById("signupBtn").addEventListener("click",o);const t=document.createElement("div");t.style.position="fixed",t.style.top="20px",t.style.right="20px",t.style.background="red",t.style.color="white",t.style.padding="15px",t.style.display="none",t.style.zIndex="1",document.body.appendChild(t);function o(){fetch("partials/registration.html").then(n=>n.text()).then(n=>{const $=document.getElementById("registrationModalContainer");$.innerHTML=n;const x=document.getElementById("registrationForm"),C=document.querySelector(".close-icon");x.addEventListener("submit",function(O){O.preventDefault();const d=document.getElementById("name").value,g=document.getElementById("email").value,p=document.getElementById("password").value;if(d&&g&&p){console.log("User data:",{name:d,email:g,password:p});const a={name:d,email:g,password:p};localStorage.setItem("userData",JSON.stringify(a)),r()}else{const a=[];d||a.push("Name"),g||a.push("Email"),p||a.push("Password"),t.textContent=`Please fill in the following fields: ${a.join(", ")}`,t.style.display="block",setTimeout(function(){t.style.display="none"},1e4)}}),C.addEventListener("click",function(){t.style.display="none",r()})}).catch(n=>console.error("Error loading registration content:",n))}function r(){const n=document.getElementById("registrationModalContainer");n.innerHTML=""}});const y=document.querySelector(".back-to-top");window.addEventListener("scroll",U);y.addEventListener("click",T);function U(){const e=window.pageYOffset,t=document.documentElement.clientHeight;e>t?y.classList.add("back-to-top--show"):y.classList.remove("back-to-top--show")}function T(){window.pageYOffset>0&&(window.scrollBy(0,-25),setTimeout(T,0))}
//# sourceMappingURL=commonHelpers.js.map
